OdeToFood.Web/Models/GreetingViewModel.cs
using RepairShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RepairShop.Web.Models
{
    public class GreetingViewModel
    {
        public IEnumerable<RepairOrder> RepairOrder { get; set;}
        public string Message { get; set;}
        public string Name { get; set;}
    }
}

OdeToFood.Web/Controllers/GreetingController.cs
using System;
using RepairShop.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;

namespace RepairShop.Web.Controllers
{
    public class GreetingController : Controller
    {
        // GET: greeting
        public ActionResult Index()
        {
            var model = new GreetingViewModel();
            model.Message = ConfigurationManager.AppSettings["message"];
            return View(model);
        }
    }
}

OdeToFood.Web/Controllers/HomeController.cs
using RepairShop.Data.Services;
using RepairShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RepairShop.Web.Controllers
{
    public class HomeController : Controller
    {
        IRepairOrderData db;

        public HomeController(IRepairOrderData db)
        {
            this.db = db;
        }
        public ActionResult Index()
        {
            var model = db.GetAll();
            return View(model);
        }
    }
}

OdeToFood.Web/Controllers/RepairOrderController.cs
using RepairShop.Data.Models;
using RepairShop.Data.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RepairShop.Web.Controllers
{
    public class RepairOrderController : Controller
    {
        private readonly IRepairOrderData db;

        public RepairOrderController(IRepairOrderData db)
        {
            this.db = db;
        }

        // GET: Restaurants
        [HttpGet]
        public ActionResult Index()
        {
            var model = db.GetAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = db.Get(id);
            if(model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RepairOrder repairOrder)
        {
            if (ModelState.IsValid)
            {
                db.Add(repairOrder);
                return RedirectToAction("Details", new { id = repairOrder.Id });
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.Get(id);
            if(model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RepairOrder repairOrder)
        {
            if(ModelState.IsValid)
            {
                db.Update(repairOrder);

                return RedirectToAction("Details", new { id = repairOrder.Id });
            }
            return View(repairOrder);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.Get(id);
            if(model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection form)
        {
            db.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

OdeToFood.Web/Views/Greeting/Index.cshtml
@model RepairShop.Web.Models.GreetingViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Model.Message!

OdeToFood.Web/Views/Home/Index.cshtml
@model IEnumerable<RepairShop.Data.Models.RepairOrder>

@{
	ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>PC Repairshop</h1>

    <div>
        Welcome to the PC Repairshop
        <br>
        <br>
        Currently there are @Model.Count() repair orders in de the database.
    </div>


</div>

OdeToFood.Web/Views/RepairOrder/Create.cshtml
@model RepairShop.Data.Models.RepairOrder

@{
    ViewBag.Title = "Create";

    int nRepairParts = 1;
}   

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>RepairOrder</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StatusRepair, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.StatusRepair, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StatusRepair, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RepairParts, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.RepairParts, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RepairParts, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OdeToFood.Web/Views/RepairOrder/Delete.cshtml
@model RepairShop.Data.Models.RepairOrder

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RepairOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OdeToFood.Web/Views/RepairOrder/Details.cshtml
@model RepairShop.Data.Models.RepairOrder

@{
    ViewBag.Title = "Details";
    string bgcolor;
    string status = Model.StatusRepair.ToString();
}

<h2>Details of @Html.DisplayFor(model => model.Name)</h2>

<div>
    <h4>Repair Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <br>
        <dt>
            @Html.DisplayNameFor(model => model.StatusRepair)
        </dt>

        @switch (status)
        {
            case "On_hold": bgcolor = "red"; break;
            case "Under_repair": bgcolor = "black"; break;
            case "Waiting_for_parts": bgcolor = "black"; break;
            case "Done": bgcolor = "darkgreen"; break;
            default: bgcolor = "black"; return;
        }
        <dd style="color:@bgcolor;">
            @Html.DisplayFor(model => model.StatusRepair)
        </dd>
        <br>
        <dt>
            @Html.DisplayNameFor(model => model.BeginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => Model.BeginDate)
        </dd>
        <br>
        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <br>
        <dt>
            @Html.DisplayNameFor(model => model.RepairParts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RepairParts)
        </dd>
        <br>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OdeToFood.Web/Views/RepairOrder/Edit.cshtml
@model RepairShop.Data.Models.RepairOrder

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>RepairOrder</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StatusRepair, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.StatusRepair, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StatusRepair, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BeginDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BeginDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BeginDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RepairParts, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RepairParts, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RepairParts, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OdeToFood.Web/Views/RepairOrder/Index.cshtml
@model IEnumerable<RepairShop.Data.Models.RepairOrder>

@{
    ViewBag.Title = "Index";
}

<h2>
    All registered repair orders
</h2>

<p>
    @Html.ActionLink("Create New Repair Order", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StatusRepair)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeginDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.BeginDate <= DateTime.Today)
        {
            string bgcolor;
            string status = item.StatusRepair.ToString();

            <tr style='background-color:lightcoral;'>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                    @switch (status)
                    {
                        case "On_hold": bgcolor = "red"; break;
                        case "Under_repair": bgcolor = "black"; break;
                        case "Waiting_for_parts": bgcolor = "black"; break;
                        case "Done": bgcolor = "darkgreen"; break;
                        default: bgcolor = "black"; return;
                    }

                <td style="color:@bgcolor;">
                    @Html.DisplayFor(modelItem => item.StatusRepair)
                    
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.BeginDate)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
        else
        {
            string bgcolor;
            string status = item.StatusRepair.ToString();

            <tr style='background-color:white;'>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                    @switch (status)
                    {
                        case "On_hold": bgcolor = "red"; break;
                        case "Under_repair": bgcolor = "black"; break;
                        case "Waiting_for_parts": bgcolor = "black"; break;
                        case "Done": bgcolor = "darkgreen"; break;
                        default: bgcolor = "black"; return;
                    }

                <td style="color:@bgcolor;">
                    @Html.DisplayFor(modelItem => item.StatusRepair)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.BeginDate)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    }

</table>

OdeToFood.Web/Views/RepairOrder/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<h2>Sorry!</h2>

<div>We couldn't find that repair</div>

@Html.ActionLink("Back to List", "Index")

OdeToFood.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Repair orders", "Index", "RepairOrder")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>